MONGODB_HOST: mongodb-{{ env }}.0gworld.shop
REDIS_HOST: redis-{{ env }}.0gworld.shop
CATALOGUE_HOST: catalogue-{{ env }}.0gworld.shop
CART_HOST: cart-{{ env }}.0gworld.shop
USER_HOST: user-{{ env }}.0gworld.shop
RABBITMQ_HOST: rabbitmq-{{ env }}.0gworld.shop
MYSQL_HOST: mysql-{{ env }}.0gworld.shop
SHIPPING_HOST: shipping-{{ env }}.0gworld.shop
PAYMENT_HOST: payment-{{ env }}.0gworld.shop
